import nlp from "compromise";
const stopWords = new Set([
    "January",
    "February",
    "March",
    "April",
    "May",
    "June",
    "July",
    "August",
    "September",
    "October",
    "November",
    "December",
    "Summer",
    "Winter",
    "Spring",
    "Autumn",
    "Sydney",
    "Sydney",
  "Harbin",
  "Dubai",
  "Venice",
  "New Orleans",
  "Rio de Janeiro",
  "Tokyo",
  "Austin",
  "Dublin",
  "Kyoto",
  "Amsterdam",
  "New York City",
  "Cannes",
  "Vienna",
  "Las Vegas",
  "Glastonbury",
  "Paris",
  "Athens",
  "Pamplona",
  "Calgary",
  "Quebec City",
  "Edinburgh",
  "Black Rock Desert",
  "Munich",
  "Albuquerque",
  "Salem",
  "Chiang Mai",
  "Singapore",
  "Brest",
  "Normandy",
  "Philadelphia",
  "Porto",
  "Sopot",
  "São Paulo",
  "San Sebastián",
  "Bologna",
  "Barcelona",
  "Helsinki",
  "Zurich",
  "Rotterdam",
  "Hong Kong",
  "Milan",
  "Los Angeles",
  "Berlin",
  "San Francisco",
  "Frankfurt",
  "Jaipur",
  "Toronto",
  "Miami",
  "Sharjah",
  "Melbourne",
  "Prague",
  "Nuremberg",
  "Strasbourg",
  "Tenerife",
  "Santa Cruz",
  "Boston",
  "Gettysburg",
  "Lisbon",
  "Holland",
  "Washington D.C.",
  "Arts and Culture Festivals",
  "Ice and Snow Sculptures",
  "Shopping Festivals",
  "Carnivals",
  "Anime and Gaming Expos",
  "Literary Festivals",
  "Flower Festivals",
  "Film Festivals",
  "Music Festivals",
  "Historic Reenactments",
  "Halloween Celebrations",
  "Food Festivals",
  "Christmas Markets",
  "Winter Sports Events",
  "Polo Tournaments",
  "Fashion Weeks",
  "Automotive Shows",
  "Food and Wine Festivals",
  "Jazz Festivals",
  "Theater and Performing Arts",
  "Parades and Street Parties",
  "Maritime Festivals",
  "Indie Music Festivals",
  "Culinary Events",
  "Comedy Festivals",
  "Lantern Festivals",
  "Haunted Attractions"
]);

export default function extractKeywords(sentence) {
    const doc = nlp(sentence);
    const terms = doc.terms().out("array");
    const keywords = terms.filter((word) => !stopWords.has(word.toLowerCase()));
    return keywords;
}