import nlp from "compromise";
const stopWords = new Set([
    "ride",
    "book",
    "cancel",
    "track",
    "driver",
    "safety",
    "traffic",
    "fare",
    "route",
    "pickup",
    "drop-off",
    "app",
    "estimate",
    "ETA",
    "payment",
    "cashless",
    "ride-sharing",
    "vehicle",
    "insurance",
    "emergency",
    "report",
    "complaint",
    "review",
    "rating",
    "loyalty",
    "promo",
    "discount",
    "policy",
    "child seat",
    "pet",
    "carpool",
    "green ride",
    "reimbursement",
    "traffic conditions",
    "surge pricing",
    "rider behavior",
    "passenger",
    "driver behavior",
    "road safety",
    "seatbelt",
    "GPS",
    "routes",
    "navigation",
    "notification",
    "emergency contact",
    "support",
    "feedback",
    "cancelation fee",
    "inappropriate behavior",
    "driving norms",
    "alcohol policy",
    "rider safety",
    "cancellation",
    "pickup location",
    "drop-off location",
    "wait time",
    "traffic updates",
    "roadblocks",
    "detour",
    "address",
    "loyalty points",
    "ride history",
    "scheduled rides",
    "front seat",
    "safety features",
    "child policy",
    "ride duration",
    "complaint process",
    "feedback mechanism",
    "payment methods",
    "ride tracking",
    "driver contact",
    "picking up passengers",
    "traffic rules",
    "ride options",
    "app settings",
    "terms of service",
    "privacy",
    "driver details",
    "rider preferences",
    "cancellation policy",
    "referral",
    "safe driving",
    "communication",
    "accessibility",
    "trip sharing",
    "fare breakdown",
    "ride types",
    "trip duration",
    "comfort",
    "car maintenance",
    "driver training",
    "insurance coverage",
    "service area",
    "promotions",
    "driver requirements",
    "wait time",
    "safety guidelines",
    "contact support",
    "ride disruptions",
    "driving distance",
    "emergency response",
    "rider guidelines",
    "ride-sharing services",
    "safety protocols",
    "COVID-19 measures",
    "rider obligations",
    "responsibility",
    "pet policy",
    "feedback system",
    "traffic laws",
    "online booking",
    "terms and conditions",
    "guidelines",
    "rider identification",
    "ride completion",
    "customer service",
    "trip cancellation",
    "driver rating",
    "communication channel",
    "multi-passenger rides",
    "tipping",
    "passenger count",
    "support channels",
    "driver communication",
    "code of conduct",
    "rider etiquette",
    "arrival time",
    "pickup time",
    "privacy policy",
    "user account",
    "ride history",
    "confirmation",
    "cancellation window",
    "rider support",
    "contact information",
    "app features",
    "ride app",
    "safety tips",
    "neighborhood safety",
    "driver profiles",
    "behavioral norms",
    "user reviews",
    "rider safety tips",
    "vehicle type",
    "ride ratings",
    "address verification",
    "incident reporting",
    "safety alerts",
    "driver verification",
    "ride conditions",
    "service reviews",
    "ride limits",
    "delay notifications",
    "passenger behavior",
    "transportation options",
    "booking confirmation",
    "rider safety measures",
    "driving regulations",
    "local laws",
    "safety checks",
    "health guidelines",
    "vehicle inspection",
    "driver standards",
    "payment security",
    "account settings",
    "route optimization",
    "user interface",
    "real-time updates",
    "in-app messaging",
    "ride preferences",
    "trip analytics",
    "incident management",
    "frequent routes",
    "app usability",
    "user engagement",
    "ride allocation",
    "personal safety",
    "operational hours",
    "traffic congestion",
    "ride scheduling",
    "multi-stop rides",
    "app notifications",
    "account verification",
    "user experience",
    "commuting options",
    "driver shifts",
    "fare adjustments",
    "shared rides",
    "premium service",
    "service feedback",
    "user anonymity",
    "ride metrics",
    "seat availability",
    "vehicle comfort",
    "trip efficiency",
    "driver app",
    "safety training",
    "rider protection",
    "traffic patterns",
    "ride disputes",
    "community guidelines",
    "ride-sharing network",
    "account history",
    "app performance",
    "frequent rider",
    "driver pickup",
    "route suggestions",
    "ride tracking features",
    "service interruptions",
    "scheduled rides",
    "car service",
    "emergency procedures",
    "driver response",
    "rider guidelines",
    "service limitations",
    "ride flexibility",
    "traffic signals",
    "weather impact",
    "service enhancements",
    "app reviews",
    "driver rewards",
    "user guidelines",
    "ride customization",
    "driver training programs",
    "travel behavior",
    "safety standards",
    "platform policies",
    "service accessibility",
    "payment processing",
    "trip planning",
    "ride-sharing trends",
    "digital footprint",
    "rider loyalty",
    "traffic violations",
    "insurance requirements",
    "passenger comfort",
    "ride options",
    "vehicle cleanliness",
    "driver incentives",
    "app updates",
    "safety assessments",
    "service commitment",
    "account management",
    "community involvement",
    "user safety",
    "driver engagement",
    "ride satisfaction",
    "vehicle regulations",
    "feedback collection",
    "trip logs",
    "driver-client relationship",
    "transportation safety",
    "insurance claims",
    "local ride services",
    "app integrations",
    "vehicle features",
    "safety audits",
    "risk management"
]);

export default function extractKeywords(sentence) {
    const doc = nlp(sentence);
    const terms = doc.terms().out("array");
    const keywords = terms.filter((word) => !stopWords.has(word.toLowerCase()));
    return keywords;
}